FROM ubuntu:16.04
RUN apt-get update
RUN apt-get install -y mongodb-server ruby-full ruby-dev build-essential git curl

RUN git clone -b monolith https://github.com/express42/reddit.git
#RUN git clone https://github.com/Artemmkin/reddit.git

COPY mongod.conf /etc/mongod.conf
COPY db_config /app/db_config
COPY start.sh /start.sh

RUN gpg --keyserver hkp://pool.sks-keyservers.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3 7D2BAF1CF37B13E2069D6956105BD0E739499BDB
RUN \curl -L https://get.rvm.io | bash -s stable
#RUN /bin/bash -l -c "gem install bundler"
#RUN gem install bundler
#RUN source /etc/profile.d/rvm.sh
#RUN echo "source $HOME/.rvm/scripts/rvm" >> ~/.bash_profile
#RUN rvm install 3.0.0

RUN gem install bundler
RUN cd /reddit && bundle install
RUN mkdir -p /data/db
RUN chmod 0777 /start.sh

CMD ["/start.sh"]
